# The Sonar Bitbucket plug-in will run on the default Pipeline.
# -----
image: emeraldsquad/sonar-scanner

pipelines:
  branches:
    develop:
      - step:
          script:
            - npm install -D typescript
            - sonar-scanner -Dsonar.host.url=https://sonarqube.tools.stg.tekoway.com
    master:
      - step:
          script:
            - npm install -D typescript
            - sonar-scanner -Dsonar.host.url=https://sonarqube.tools.stg.tekoway.com
